### ISSUE TITLE
Improve ln.setup.settings docstring

### ISSUE THREAD

**Issue by Zethson** [laminlabs/lamindb-setup#894]
https://docs.lamin.ai/lamindb.setup.settings

![image](https://github.com/user-attachments/assets/5ca4ae99-a6de-44f0-bed1-f04f256d19d0)

This doesn't look great.

**Comment by Koncopd** [comment]
Ok, this happens by default because it shows `__repr__` of `settings` as runtime.
@falexwolf do we have a way to understand that a doc building session is running at runtime? Then we can correct [here](https://github.com/laminlabs/lamindb-setup/blob/5fa441c594bd7e2dfd6e78cde5f9f39b01ac3e63/lamindb_setup/core/_settings.py#L173) at runtime to avoid this. Maybe an env variable or something like this to check if the docs are being built now?

**Comment by Zethson** [comment]
A bit hacky but I'm using this in bionty: https://github.com/laminlabs/bionty/blob/main/bionty/models.py#L413

**Comment by Koncopd** [comment]
Thanks, i think checking for sphynx is fine here also.
